# Generated by Django 3.0.6 on 2020-06-04 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20200604_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 6, 4, 9, 25, 52, 348397, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
    ]
