# Generated by Django 3.0.6 on 2020-06-06 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_auto_20200604_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 3, 9, 342055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 3, 9, 343054, tzinfo=utc)),
        ),
    ]
