# Generated by Django 3.0.6 on 2020-06-06 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_auto_20200606_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 5, 3, 486402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 5, 3, 487401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 5, 3, 485402, tzinfo=utc)),
        ),
    ]
