# Generated by Django 3.0.6 on 2020-06-06 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0007_auto_20200606_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 25, 33, 419032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 25, 33, 420031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sportnews',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 6, 12, 25, 33, 419032, tzinfo=utc)),
        ),
    ]
